### ISSUE TITLE
[BUG] Can't install nor launch Lazap

### ISSUE THREAD

**Issue by PorkingMane** [Lazap-Development/Lazap#133]
Can't fully install nor launch Lazap, would summon Microsoft Edge Updater which wont let installer complete
OS: Windows 10 (Atlas Edition with full compatibility)
![2023-04-29_05-19-24](https://user-images.githubusercontent.com/116605791/235263598-65ff73a7-f656-498f-a11e-6971f7384ae0.gif)

p.s. hope that this is my Atlas problem and not program, cuz it looks dope and probably would surpass playnite

**Comment by p0ryae** [comment]
Thank you for opening this issue and bringing this into attention.

Unfortunately, Lazap depends on webview2 in order to present the UI. After a bit of research, AtlasOS developers in their OS documentation have mentioned that WebView is not a part of the operating system.

More Information: https://docs.atlasos.net/troubleshooting/removed-features/

The solution to this problem is installing [Evergreen Standalone](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) which supplies WebView2:

![image](https://user-images.githubusercontent.com/59381835/235271572-660e2113-e916-4fde-8794-a99d4fc86919.png)

Download and install the right architecture, then attempt re-installing lazap and running it.

**Comment by PorkingMane** [comment]
Oh, thanku! All works now!
